# SwiftLint Configuration for GitLab Mobile

# Lint sources only
included:
  - "Movies/Movies/**/*.swift"        # Main app sources
  - "Packages/**/Sources/**/*.swift"  # Local package sources

# Globally exclude build artifacts
excluded:
  - .build
  - build
  - DerivedData
  - build/
  - DerivedData/
  - SourcePackages
  - Pods
  - .swiftpm
  - Carthage
  - ".build/**"
  - "build/**"
  - "**/SourcePackages/**"
  - "**/checkouts/**"
  - "**/*.xcodeproj/**"
  - "**/*.xcworkspace/**"
  - "**/ModuleCache.noindex/**"
  - "**/Index.noindex/**"
  # Tests
  - "**/Tests/**"
  - "**/*Tests*/**"
  - "**/*Test*.swift"
  - "**/*Spec*.swift"

# Opt-in rules for better code quality
opt_in_rules:
  - empty_count
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - unused_optional_binding
  - no_space_in_method_call
  - force_unwrapping
  - large_tuple
  - weak_delegate

# Analyzer rules (for unused_import)
analyzer_rules:
  - unused_import

# Custom rules
line_length:
  warning: 130
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

large_tuple:
  warning: 3
  error: 5

trailing_comma:
  mandatory_comma: true

identifier_name:
  min_length: 3
  max_length: 40
  excluded: [id, URL, API, URLSession]

todo:
  severity: warning

cyclomatic_complexity:
  warning: 10
  error: 20
